/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpa.demo;

import java.util.List;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import jpa.demo.dao.DepartmentDao;
import jpa.demo.dao.EmployeeDao;
import jpa.demo.model.Department;
import jpa.demo.model.Employee;

public class App {
	
	private static EntityManagerFactory emfactory;
	private static EntityManager entitymanager;

	public static void main(String[] args) {
		
		emfactory = Persistence.createEntityManagerFactory("JpaPersistenceUnit");
		entitymanager = emfactory.createEntityManager();
		
		DepartmentDao departmentDao = new DepartmentDao(entitymanager);
		EmployeeDao employeeDao = new EmployeeDao(entitymanager);
		
		Department department = createDepartment(departmentDao);		
		createEmployees(employeeDao, department);
		
		List<Department> departments = departmentDao.getAll();
		for (Department dep : departments) {
			System.out.println("Department name = " + dep.getName());
			Set<Employee> employees = dep.getEmployeeList();
			for (Employee emp : employees) {
				System.out.println("Employee name = " + emp.getEname() + ", " + emp.getElastName());				
			}
		}
		
		department.setName("swf");
		departmentDao.update(department);
		departmentDao.delete(department);		

		entitymanager.close();
		emfactory.close();

	}

	private static void createEmployees(EmployeeDao employeeDao, Department department) {
		Employee e1 = new Employee();
		e1.setEname("Leandro");
		e1.setSalary(40000);
		e1.setElastName("Gimenez");
		department.addEmployee(e1);
		employeeDao.save(e1);
		
		Employee e2 = new Employee();
		e2.setDepartment(department);
		e2.setEname("Victoria");
		e2.setSalary(25000);
		e2.setElastName("Gimenez");
		department.addEmployee(e2);
		employeeDao.save(e2);
	}

	private static Department createDepartment(DepartmentDao departmentDao) {
		Department department = new Department();
	    department.setName("Development");
		departmentDao.save(department);
		return department;
	}
}
